"""empty message

Revision ID: f3bb34fdc98e
Revises: 
Create Date: 2021-05-21 12:55:46.601630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3bb34fdc98e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_date_created'), 'node', ['date_created'], unique=False)
    op.create_index(op.f('ix_node_date_updated'), 'node', ['date_updated'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('edge',
    sa.Column('source', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['source'], ['node.id'], ),
    sa.ForeignKeyConstraint(['target'], ['node.id'], ),
    sa.PrimaryKeyConstraint('source', 'target')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge')
    op.drop_table('user')
    op.drop_index(op.f('ix_node_date_updated'), table_name='node')
    op.drop_index(op.f('ix_node_date_created'), table_name='node')
    op.drop_table('node')
    # ### end Alembic commands ###
